DELETE FROM PSX_PUBLICATION_SITE_ITEM 
WHERE REFERENCE_ID IN 
(SELECT REFERENCE_ID 
FROM PSX_PUBLICATION_DOC 
WHERE STATUS_ID = 126661)

--
DELETE FROM PSX_PUBLICATION_DOC 
WHERE STATUS_ID = 126661 

--
DELETE FROM PSX_PUBLICATION_STATUS 
WHERE STATUS_ID = 126661

