sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\alterTable.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\search_getNeighbor.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\taxonomySplit.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\taxonomy_getMonthlyAgg.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\taxonomy_getTaxonLabel.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\taxonomy_getTaxons.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\tr_taxonomyInsert.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\tr_taxonomyInsert_staging.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\tr_taxonomyUpt.sql
sqlcmd -l 0 -S %1  -E -I -d percCancergov -i percCancergov\tr_taxonomyUpt_staging.sql
sqlcmd -l 0 -S %1  -E -I -d percussion -i percussion\listUniqueTitleUpdate.sql