IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[t_NCIViewOnDELETE]') AND OBJECTPROPERTY(id, N'IsTrigger') = 1)
EXEC dbo.sp_executesql @statement = N'BEGIN
	INSERT INTO AuditNCIView(AuditActionType,
		NCIViewID,
		NCITemplateID,
		NCISectionID,
		GroupID,
		Title,
		ShortTitle,
		[Description],
		URL,
		URLArguments,
		MetaTitle,
		MetaDescription,
		MetaKeyword,
		CreateDate,
		ReleaseDate,
		ExpirationDate,
		Version,
		Status,
		IsOnProduction,
		IsMultiSourced,
		IsLinkExternal,
		SpiderDepth,
		UpdateDate,
		UpdateUserID,
		PostedDate,
		DisplayDateMode,
		ReviewedDate,
		ChangeComments) 
	SELECT ''DELETE'' as AuditActionType,
		tbl.NCIViewID,
		tbl.NCITemplateID,
		tbl.NCISectionID,
		tbl.GroupID,
		tbl.Title,
		tbl.ShortTitle,
		tbl.[Description],
		tbl.URL,
		tbl.URLArguments,
		tbl.MetaTitle,
		tbl.MetaDescription,
		tbl.MetaKeyword,
		tbl.CreateDate,
		tbl.ReleaseDate,
		tbl.ExpirationDate,
		tbl.Version,
		tbl.Status,
		tbl.IsOnProduction,
		tbl.IsMultiSourced,
		tbl.IsLinkExternal,
		tbl.SpiderDepth,
		tbl.UpdateDate,
		tbl.UpdateUserID,
		tbl.PostedDate,
		tbl.DisplayDateMode,
		tbl.ReviewedDate,
		tbl.ChangeComments
	FROM 	deleted  tbl
END



' 
GO
