insert dbo.autosuggest_en_misspell(termname,misspell) values ('AccrualNet','accrual net')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('acupuncture','accupuncture')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma','adencarcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenoma','adeno')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma','adeno carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma ','adenocarcenoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma','adenocarinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma ','adinocarcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adjuvant','adjuvent')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adenocarcinoma','adnocarcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('adrenocortical carcinoma','adrenal cortical carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Alimta','alimpta')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Alimta','altima')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('anal cancer','analcancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('anastrozole','anastrazole')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('anastrozole','anastrozol')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('angiogenesis','angiogenisis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('angiogenesis','angiogensis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('antioxidants','antioxidents')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Arimidex','arimadex')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Arimidex','arimedex')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Arimidex','armidex')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('artificial sweeteners','artificial sweetners')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('aspartame','aspertame')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('aspirin','asprin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('astrocytoma','astro')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Barrett esophagus','barrets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('basal cell','basel cell')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('basal cell carcinoma','basel cell carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('basal cell','basil cell')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('basal cell carcinoma','basil cell carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','beast cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('biopsy','biospy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('bone metastasis','bone metastisis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('bone metastasis','bone mets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('BRCA1','brac 1')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('BRCA1','brac1')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('BRCA2','brac2')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('BRCA','braca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('brachytherapy','brachy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('brachytherapy','brachy therapy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('brain metastasis','brain mets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('brain stem glioma','brainstem glioma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','brast cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breast ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breast cacner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breast cance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer chemotherapy','breast cancer chemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Breast Cancer Risk Assessment Tool','breast cancer risk assesment tool')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer statistics','breast cancer stats')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breastcancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breat cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','breats cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast','brest')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('breast cancer','brest cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Burkitt lymphoma','burketts lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cancer statistics','cancer stats')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cancer symptoms','cancer symtoms')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('carcinoma','carcenoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('carcinoma','carsanoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('carcinoma','carsinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('carcinoma','carsonoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cervical cancer','cerival cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cervical cancer','cervial cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cervical cancer','cervical caner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy and you','chemo and you')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy drugs','chemo drugs')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemoembolization','chemo embolization')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy side effects','chemo side effects')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemo therapy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy treatment','chemo treatment')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemoterapy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemotheraphy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemotherepy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemotheropy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','chemotherpy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chondrosarcoma','chrondosarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cervical cancer','cirvical cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('clinical trials','clincal trials')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('clinical trials','clincial trials')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colon cancer','colan cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colon cancer','colin cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colon cancer','colon ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colon cancer','colon cance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colon cancer','colon caner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colonoscopy ','colonscopy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('colonoscopy','coloscopy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('complementary','complimentary')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cryotherapy','cryo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('CTCAE','ctae')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('CTCAE','ctc ae')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('cryosurgery','cyrosurgery')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Cytoxan ','cytoxin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('deodorant','deoderant')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('diarrhea','diarrhoea')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('endometrial cancer','endrometrial cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esophagal cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esophegeal cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esophgeal cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal','esophogeal')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esophogeal cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophagus ','esophogus')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esophogus cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('esophageal cancer','esphogeal cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ethical','ethic')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('fact sheet','factsheet')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('fact sheets','factsheets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('fatigue ','fatique')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Femara','femera')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('financial assistance','fiancial assistance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('financial assistance','financial assitance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('financial organizations','financial orgs')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('fluorouracil','flourouracil')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('follicular lymphoma','folicular lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gail model','gale model')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('gallbladder','gall bladder')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('gallbladder cancer','gall bladder cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('gall bladder','gallblader')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gardasil','gardisil')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('gastric cancer','gastric ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('gastrointestinal','gastro')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gemzar','gemsar')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('glioblastoma','gioblastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gleason score','gleeson')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gleason score','gleeson score')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gleevec','gleevac')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('glioblastoma','gliobastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('glioblastoma multiforme','glioblastoma multiform')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Gonzalez','gonzales')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('hepatitis C','hep c')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('HIPAA','hippa')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodgekins')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodgekins lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodkin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodkin lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodking')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodkins')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','hodkins lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('human papillomavirus','human papilloma virus')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('inflammatory','inflamatory')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('inflammatory breast cancer','inflamatory breast cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('interferon','interfuron')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('intraperitoneal chemotherapy','intraperitoneal chemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Kaposi sarcoma','karposi')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','kemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('chemotherapy','kimo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('laetrile','laetril')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('laetrile','leatril')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leiomyosarcoma','leimyosarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leiomyosarcoma','leiomysarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('letrozole','letrazole')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('letrozole','letrozol')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leukemia','leukima')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leukemia','leukimia')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leukemia','leusemia')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leiomyosarcoma','lieomyosarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','limfoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','limphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Hodgkin lymphoma','linfoma hodking')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('non-Hodgkin lymphoma','linfoma no hodking')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('liver metastasis','liver mets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('liver cancer','livercancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leukemia','luekemia')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('leukemia','lukemia')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lung cancer','lung ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lung cancer','lung cacner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lung cancer symptoms','lung cancer symtoms')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lung cancer','lung caner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lung cancer','lungcancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymph nodes','lymp nodes')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphedema','lympedema')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphedema','lymphadema')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymph node','lymphnode')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymph node','lymphnodes')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lymphnoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphedema','lymphodema')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lymphomia')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lymphona')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lympoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lynphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphedema','lyphedema')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('lymphoma','lyphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','malanoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mammogram','mammagram')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mammogram','mamogram')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mammograms','mamograms')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mammography','mamography')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mantle','mantel')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mantle cell','mantel cell')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mantle cell lymphoma','mantel cell lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mastectomy','masectomy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Medrol','medra')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('MedDRA codes','medra codes')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('medulloblastoma','meduloblastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','melanom')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','melenoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','melinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','melonoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Merkel cell','merkle cell')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('mesothelioma','mesothilioma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastasis','metasis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastasis','metastasi')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastatic','metastic')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastatic breast cancer','metastic breast cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastatic cancer','metastic cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastatic liver cancer','metastic liver cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastasis','metastisis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastasis','metastisize')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('metastasis','mets')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('multiple myeloma','multiple mylenoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('multiple myeloma','multiple myleoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('multiple myeloma','multiple myloma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('multiple myeloma','multiple myoloma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('multiple myeloma','mutiple myeloma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myelodysplastic','myelodisplastic')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myelodysplastic syndromes','myelodisplastic syndrome')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myeloma','mylenoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myelofibrosis','myleofibrosis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myeloma','myleoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('myeloma','myloma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('nanotechnology','nano')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('nanotechnology','nanotech')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('national organization','national org')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('national organizations','national orgs')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('NCCCP','nccp')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('neuroblastoma','neoblastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('neuroblastoma','neroblastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('neuroendocrine','neuro endocrine')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('non-Hodgkin lymphoma','no hodking')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('non-Hodgkin lymphoma','non hodgekins lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('non-Hodgkin lymphoma','non hodkins lymphoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('melanoma','non melanoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('neuroblastoma','nueroblastoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('nutrition','nutrtion')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Office of Communications and Education','office of communication')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('organization chart','org chart')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('osteosarcoma','osteo sarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ovarian cancer','ovarian ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ovarian cancer','ovariancancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ovarian cancer','ovarion cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ovarian','overian')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ovarian cancer','overian cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pancreatic cancer','pacreatic cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('palliative care','paliative care')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('palliative care','pallative care')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pancreatic cancer','pancratic cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pancreas','pancrea')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Papanicolaou','papanicolao')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Papanicolaou','papanicolau')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('papillomavirus','papiloma virus')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pheochromocytoma','pheo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pheochromocytoma','pheocromocytoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('photodynamic therapy','photo dynamic therapy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pictures','pics')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Pink Book','pinkbook')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('plasmacytoma','plasma cytoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('postdoctoral','post doc')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('postdoctoral','post doctoral')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('postdoctoral','postdoc')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('postdoctoral','postdoctor')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate cancer','prostae cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate','prostat')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate cancer','prostate ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate ','prostrate')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate cancer','prostrate cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('prostate cancer','protate cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('pruritus','pruritis')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('PubMed','pub med')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('quitting smoking','quiting smoking')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('rhabdomyosarcoma','rabdomyosarcoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('radiation','radation')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('radiation therapy','radiation theraphy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('radiofrequency ablation','radio frequency ablation')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('radiotherapy','radiotheraphy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('radiation','radition')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('raloxifene','raloxifen')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('recurrence','recurrance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('recurrence','reoccurance')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Rituxan','retuxin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Revlimid','revlamid')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('rhabdomyosarcoma','rhabdo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('risk assessment','risk assesment')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Rituxan','rituxin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('R-01','ro1')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('R-03','ro3')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('sarcoma','sacroma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('sentinel lymph node biopsy','sentinal node biopsy')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('side effects','side affects')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('side effects of chemotherapy','side effects of chemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('skin cancer','skin caner')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('skin cancer','skincancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('small cell lung cancer','small cell lung ca')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('squamous','squamish')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('squamous cell','squamos')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('squamous cell carcinoma','squamos cell carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('squamous','squamus')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('squamous cell carcinoma','squamus cell carcinoma')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('stomach cancer','stomac cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('stomach cancer','stomache cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('survival rate','survial rate')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('surviving','survivin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('symptoms','symptons')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('symptoms','symtoms')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('symptoms of cancer','symtoms of cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('symptoms of cervical cancer','symtoms of cervical cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('symptoms','syptoms')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tobacco','tabacco')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tamoxifen','tamoxifan')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tamoxifen','tamoxifin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tamoxifen','tamoxiphen')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tamoxifen','tamoxofin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Temodar','temador')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('temozolomide','temozolamide')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('testicle','testical')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('testicular cancer ','testical cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('thyroid','throid')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('thyroid','thyriod')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('TNM','tmn')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tamoxifen','tomoxifen')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tongue','tounge')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tongue cancer ','tounge cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('TRAIL','trail')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tumor','tumer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('tumors','tumers')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('types of chemotherapy','types of chemo')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('thyroid cancer','tyroid cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('ultrasound','ultra sound')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('urethral cancer','ureteral cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('uterine cancer','uteran cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('uterine cancer','uterian cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('uterine','uterin')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('uterine cancer','uterin cancer')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('vitamin D','vit d')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('wyntk','wyktk')
insert dbo.autosuggest_en_misspell(termname,misspell) values ('Zometa','zomeda')

------------------------

insert dbo.autosuggest_es_misspell(termname,misspell) values ('cáncer de cuello uterino','cancer cervico uterino')
insert dbo.autosuggest_es_misspell(termname,misspell) values ('linfoma de Hodgkin','linfoma de hodking')
insert dbo.autosuggest_es_misspell(termname,misspell) values ('linfoma no Hodgkin ','linfoma no hodkin')
insert dbo.autosuggest_es_misspell(termname,misspell) values ('quimioterapia','quimio')
insert dbo.autosuggest_es_misspell(termname,misspell) values ('quimioterapia','quimoterapia')