create table percReport_contenttype(contenttypename varchar(700), type varchar(100))

insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerTypePortalHomeGeneral','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerTypePortalHome','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerTypePortalHomeList','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvBooklet ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerBulletin','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerTypeHome ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvClinicalTrialResult ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvDrugInfoSummary ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvFactSheet ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvFeaturedClinicalTrial ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvPowerPoint','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvPressRelease ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('gloImage ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('gloVideo ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciAppModulePage ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciErrorPage ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciFile ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciGeneral ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciHome ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciLandingPage ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('pdqCancerInfoSummary ','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('pdqDrugInfoSummary','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvContentSearch','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvTopicSearchCategory','page')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvBanner','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvBookletPage','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvCancerBulletinPage','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvDocTitleBlock','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvDynamicList','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvMicrositeIndex','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvPageOptionsBox','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvPowerPointPage','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvSiteFooter','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvTileCarousel','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvTimelyContentBlock','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvTimelyContentFeature','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvTopicSearch','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciAppWidget','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciContentHeader','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciDocFragment','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciForm','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciImage','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciLink','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciList','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciSectionNav','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('nciTile','supporting')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvAutoRSS','content')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvBestBetsCategory','content')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvPromoUrl','content')
insert dbo.percreport_contenttype(contenttypename,type) values ('cgvManualRSS','content')